require 'uldd/fhlmc/valuation_type'

describe Fhlmc::ValuationType do

  class TestScenario < Struct.new(:name, :RWTAppraisalType, :FieldworkObtained, :PropertyValMethod, :AVMModelName,
                             :ProductCode, :expected_valuation_type, :expected_avm_model, 
                             :expected_additional_investor_features, :expected_valuation_form, 
                             :expected_valuation_other_description)
    def initialize(opts = {})
      self.name = opts.fetch(:name, 'name unspecified')

      [ :name, :RWTAppraisalType, :FieldworkObtained, :PropertyValMethod, :AVMModelName,
        :ProductCode, :expected_valuation_type, :expected_avm_model, 
        :expected_additional_investor_features, :expected_valuation_form, 
        :expected_valuation_other_description,
      ].each do |sym|
        self.public_send(assignify(sym), opts.fetch(sym, nil))
      end
    end

    private 
    def assignify(sym)
      (sym.to_s + '=').to_sym
    end
  end

  scenarios = [
    TestScenario.new(
      name: "line 3",
      RWTAppraisalType: 1004,
      FieldworkObtained: "Form 1004 appraisal with interior/exterior inspection",
      PropertyValMethod: "ANY",
      AVMModelName: 'ANY',
      ProductCode: 'ANY',
      expected_valuation_type: 'FullAppraisal',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: "UniformResidentialAppraisalReport",
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 4",
      RWTAppraisalType: 1004,
      FieldworkObtained: "Form 1004C, Manufactured Home Appraisal Report with Interior/exterior inspection",
      PropertyValMethod: "ANY",
      AVMModelName: 'ANY',
      ProductCode: 'ANY',
      expected_valuation_type: 'FullAppraisal',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: "ManufacturedHomeAppraisalReport",
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 5",
      RWTAppraisalType: 1004,
      FieldworkObtained: "Form 1004D appraisal updated/completion report",
      PropertyValMethod: "ANY",
      AVMModelName: 'ANY',
      ProductCode: 'ANY',
      expected_valuation_type: 'FullAppraisal',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: "AppraisalUpdateAndOrCompletionReport",
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 6",
      RWTAppraisalType: 1025,
      FieldworkObtained: "Form 1025 appraisal with interior/exterior inspection",
      PropertyValMethod: "ANY",
      AVMModelName: 'ANY',
      ProductCode: 'ANY',
      expected_valuation_type: 'FullAppraisal',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: "SmallResidentialIncomePropertyAppraisalReport",
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 7",
      RWTAppraisalType: 1073,
      FieldworkObtained: "Form 1073 condominium appraisal with interior/exterior inspection",
      PropertyValMethod: "ANY",
      AVMModelName: 'ANY',
      ProductCode: 'ANY',
      expected_valuation_type: 'FullAppraisal',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: "IndividualCondominiumUnitAppraisalReport",
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 8",
      RWTAppraisalType: nil,
      FieldworkObtained: "Form 1075 condominium appraisal with exterior inspection",
      PropertyValMethod: "ANY",
      AVMModelName: 'ANY',
      ProductCode: 'ANY',
      expected_valuation_type: 'DriveBy',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: "ExteriorOnlyInspectionIndividualCondominiumUnitAppraisalReport",
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 9",
      RWTAppraisalType: nil,
      FieldworkObtained: "Form 2000 field review one-unit",
      PropertyValMethod: "ANY",
      AVMModelName: 'ANY',
      ProductCode: 'ANY',
      expected_valuation_type: 'Other',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: "OneUnitResidentialAppraisalFieldReviewReport",
      expected_valuation_other_description: 'FieldReview',
    ),
    TestScenario.new(
      name: "line 10",
      RWTAppraisalType: nil,
      FieldworkObtained: "Form 2000A field review 2-4",
      PropertyValMethod: "ANY",
      AVMModelName: 'ANY',
      ProductCode: 'ANY',
      expected_valuation_type: 'Other',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: "TwoToFourUnitResidentialAppraisal",
      expected_valuation_other_description: 'FieldReview',
    ),
    TestScenario.new(
      name: "line 11",
      RWTAppraisalType: nil,
      FieldworkObtained: "Form 2055 appraisal with exterior only inspection",
      PropertyValMethod: "ANY",
      AVMModelName: 'ANY',
      ProductCode: 'ANY',
      expected_valuation_type: 'DriveBy',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: "ExteriorOnlyInspectionResidentialAppraisalReport",
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 12",
      RWTAppraisalType: nil,
      FieldworkObtained: "Form 2075 exterior inspection",
      PropertyValMethod: "ANY",
      AVMModelName: 'ANY',
      ProductCode: 'ANY',
      expected_valuation_type: 'DriveBy',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: "DesktopUnderwriterPropertyInspectionReport",
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 13",
      RWTAppraisalType: nil,
      FieldworkObtained: "No appraisal/inspection obtained",
      PropertyValMethod: "FullAppraisal",
      AVMModelName: 'NA',
      ProductCode: 'C30FXD',
      expected_valuation_type: 'None',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 14",
      RWTAppraisalType: nil,
      FieldworkObtained: "No appraisal/inspection obtained",
      PropertyValMethod: "FullAppraisal",
      AVMModelName: 'NA',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'AutomatedValuationModel',
      expected_avm_model: 'HomeValueExplorer',
      expected_additional_investor_features: [ 'H03' ],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 15a",
      RWTAppraisalType: nil,
      FieldworkObtained: "No appraisal/inspection obtained",
      PropertyValMethod: "AutomatedValuationModel",
      AVMModelName: 'NA',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'AutomatedValuationModel',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 15b",
      RWTAppraisalType: nil,
      FieldworkObtained: "No appraisal/inspection obtained",
      PropertyValMethod: "AutomatedValuationModel",
      AVMModelName: 'HomeValueExplorer',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'AutomatedValuationModel',
      expected_avm_model: 'HomeValueExplorer',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 16",
      RWTAppraisalType: nil,
      FieldworkObtained: "No appraisal/inspection obtained",
      PropertyValMethod: "DesktopAppraisal",
      AVMModelName: 'NA',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'DesktopAppraisal',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 17",
      RWTAppraisalType: nil,
      FieldworkObtained: "Other",
      PropertyValMethod: "FullAppraisal",
      AVMModelName: 'NA',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'Other',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: 'FieldReview',
    ),
    TestScenario.new(
      name: "line 18",
      RWTAppraisalType: nil,
      FieldworkObtained: "Other",
      PropertyValMethod: "DesktopAppraisal",
      AVMModelName: '',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'DesktopAppraisal',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 19",
      RWTAppraisalType: nil,
      FieldworkObtained: "Other",
      PropertyValMethod: "AutomatedValuationModel",
      AVMModelName: 'HomeValueExplorer',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'AutomatedValuationModel',
      expected_avm_model: 'HomeValueExplorer',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 20",
      RWTAppraisalType: nil,
      FieldworkObtained: "NA",
      PropertyValMethod: "NA",
      AVMModelName: 'NA',
      ProductCode: 'C30FXD',
      expected_valuation_type: 'None',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 21",
      RWTAppraisalType: nil,
      FieldworkObtained: "NA",
      PropertyValMethod: "NA",
      AVMModelName: 'NA',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'AutomatedValuationModel',
      expected_avm_model: 'HomeValueExplorer',
      expected_additional_investor_features: [ 'H03' ],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 22",
      RWTAppraisalType: nil,
      FieldworkObtained: "NA",
      PropertyValMethod: "FullAppraisal",
      AVMModelName: 'NA',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'FullAppraisal',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 23",
      RWTAppraisalType: nil,
      FieldworkObtained: "NA",
      PropertyValMethod: "DriveBy",
      AVMModelName: 'NA',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'DriveBy',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 24a",
      RWTAppraisalType: nil,
      FieldworkObtained: "NA",
      PropertyValMethod: "AutomatedValuationModel",
      AVMModelName: 'NA',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'AutomatedValuationModel',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 24b",
      RWTAppraisalType: nil,
      FieldworkObtained: "NA",
      PropertyValMethod: "AutomatedValuationModel",
      AVMModelName: 'HomeValueExplorer',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'AutomatedValuationModel',
      expected_avm_model: 'HomeValueExplorer',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 25",
      RWTAppraisalType: nil,
      FieldworkObtained: "NA",
      PropertyValMethod: "DesktopAppraisal",
      AVMModelName: '',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'DesktopAppraisal',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 26",
      RWTAppraisalType: nil,
      FieldworkObtained: "Form 26-1805, Certificate of Reasonable Value for VA",
      PropertyValMethod: "",
      AVMModelName: '',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: '',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "line 27",
      RWTAppraisalType: nil,
      FieldworkObtained: "Form 26-8712, Manufactured Home appraisal Report for VA",
      PropertyValMethod: "",
      AVMModelName: '',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: '',
      expected_avm_model: '',
      expected_additional_investor_features: [],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
    TestScenario.new(
      name: "Loan number 1022262",
      RWTAppraisalType: nil,
      FieldworkObtained: "NA",
      PropertyValMethod: "None",
      AVMModelName: 'NA',
      ProductCode: 'C30FXD FR',
      expected_valuation_type: 'AutomatedValuationModel',
      expected_avm_model: 'HomeValueExplorer',
      expected_additional_investor_features: [ 'H03' ],
      expected_valuation_form: '',
      expected_valuation_other_description: '',
    ),
  ]

  scenarios.each do |scenario|
    context "In scenario #{scenario.name}" do
      let(:valuation) { Fhlmc::ValuationType.new scenario }
      it "valuation type" do
        expect(valuation.valuation_type).to eq scenario.expected_valuation_type
      end

      it "avm model" do
        expect(valuation.avm_model).to eq scenario.expected_avm_model
      end

      it "additional investor features" do
        expect(valuation.additional_investor_features).to eq scenario.expected_additional_investor_features
      end

      it "valuation form" do
        expect(valuation.valuation_form).to eq scenario.expected_valuation_form
      end

      it "other description" do
        expect(valuation.valuation_other_description).to eq scenario.expected_valuation_other_description
      end
    end
  end

end
