class LockLoanDatum < DatabaseDatamartReadonly
  belongs_to :loan_general

  CREATE_VIEW_SQL = <<-eos
      SELECT
        LOCK_LOAN_DATA_id             AS id,
        loanGeneral_Id                AS loan_general_id,
        BorrowerCreditScore           AS borrower_credit_score,
        CLTV                          AS cltv,
        CoBorrowerCreditScore         AS co_borrower_credit_score,
        EscrowWaiverIndicator         AS escrow_waiver_indicator,
        FirstTimeHomebuyer            AS first_time_homebuyer,
        GSEPropertyType               AS gse_property_type,
        HCLTV                         AS hcltv,
        InitialCAP                    AS initial_cap,
        InitialLockPerformedDate      AS initial_lock_performed_date,
        IntervalCAP                   AS interval_cap,
        LenderPaidMI                  AS lender_paid_mi,
        LifetimeCAP                   AS lifetime_cap,
        LoanAmortizationTermMonths    AS loan_amortization_term_months,
        LTV                           AS ltv,
        MIIndicator                   AS mi_indicator,
        OriginatorCompensation        AS originator_compensation,
        PerformedDate                 AS performed_date,
        PropertyCity                  AS property_city,
        PropertyCounty                AS property_county,
        PropertyState                 AS property_state,
        PropertyStreetAddress         AS property_street_address,
        PropertyStreetAddressName     AS property_street_address_name, 
        PropertyStreetAddressNumber   AS property_street_address_number,
        PropertyStreetAddressUnit     AS property_street_address_unit,
        PropertyPostalCode            AS property_postal_code,
        PropertyUsageType             AS property_usage_type,
        PurchasePriceAmount           AS purchase_price_amount,
        TotalLoanAmount               AS total_loan_amt,
        BorrowerFirstName             AS borrower_first_name,
        BorrowerLastName              AS borrower_last_name,
        CoBorrowerFirstName           AS coborrower_first_name,
        CoBorrowerLastName            AS coborrower_last_name,
        PropertyAppraisedValueAmount  AS property_appraised_value_amount,
        LoanPurposeType               AS loan_purpose_type,
        MICoveragePercent             AS mi_coverage_percentage,
        LoanMaturityTermMonths        AS maturity_term_months
      FROM       LENDER_LOAN_SERVICE.dbo.[LOCK_LOAN_DATA]
    eos

  def self.sqlserver_create_view
    CREATE_VIEW_SQL
  end
end

# [Acreage] [smallint] NULL,
# [APORIndexRate] [decimal](8, 4) NULL,
# [BankruptcyDischarge] [varchar](50) NULL,
# [BorrowerFirstName] [varchar](50) NULL,
# [BorrowerITIN] [varchar](9) NULL,
# [BorrowerLastName] [varchar](50) NULL,
# [BorrowerNoCreditScore] [bit] NULL,
# [BorrowerSSN] [varchar](9) NULL,
# [BorrowerSuffix] [varchar](4) NULL,
# [Buydown] [bit] NULL,
# [BuydownContributor] [varchar](10) NULL,
# [BuydownPlan] [varchar](10) NULL,
# [CoBorrowerCreditScore] [smallint] NULL,
# [CoBorrowerFirstName] [varchar](50) NULL,
# [CoBorrowerITIN] [varchar](9) NULL,
# [CoBorrowerLastName] [varchar](50) NULL,
# [CoBorrowerNoCreditScore] [bit] NULL,
# [CoBorrowerSSN] [varchar](9) NULL,
# [CoBorrowerSuffix] [varchar](4) NULL,
# [Comments] [varchar](500) NULL,
# [ContactEmail] [varchar](50) NULL,
# [ContactFax] [varchar](50) NULL,
# [ContactName] [varchar](50) NULL,
# [ContactPhone] [varchar](50) NULL,
# [CreditGrade] [varchar](50) NULL,
# [DebtToIncomeRatio] [decimal](8, 4) NULL,
# [DiscountAmount] [money] NULL,
# [EALevel] [varchar](10) NULL,
# [EscrowWaiverType] [varchar](20) NULL,
# [EstimatedClosingDate] [smalldatetime] NULL,
# [FinancedNumberOfUnits] [tinyint] NULL,
# [FirstTimeHomebuyer] [bit] NULL,
# [Foreclosure] [varchar](50) NULL,
# [ForeignNational] [bit] NULL,
# [FRECashOutAmount] [money] NULL,
# [FullPrepaymentPenaltyOptionType] [varchar](10) NULL,
# [FundingOption] [varchar](2) NULL,
# [GSEPropertyTypeOtherDescription] [varchar](100) NULL,
# [GSERefinancePurposeType] [varchar](50) NULL,
# [HELOCPiggybackIndicator] [bit] NULL,
# [HUDRepoIndicator] [bit] NULL,
# [InitialCAP] [decimal](8, 4) NULL,
# [InitialLockPerformedDate] [datetime] NULL,
# [InterestOnly] [bit] NULL,
# [InterestOnlyTerm] [int] NULL,
# [IntervalCAP] [decimal](8, 4) NULL,
# [LatePay120DaysTimes] [tinyint] NULL,
# [LatePay30DaysTimes] [tinyint] NULL,
# [LatePay60DaysTimes] [tinyint] NULL,
# [LatePay90DaysTimes] [tinyint] NULL,
# [LienPriorityType] [varchar](25) NULL,
# [LifetimeCAP] [decimal](8, 4) NULL,
# [LoanDocumentationType] [varchar](80) NULL,
# [LoanDocumentationTypeDescription] [varchar](100) NULL,
# [LoanDocumentationTypeOtherDescription] [varchar](100) NULL,
# [LoanMaturityTermMonths] [smallint] NULL,
# [LoanPurposeType] [varchar](50) NULL,
# [MERSNumber] [varchar](50) NULL,
# [MICoveragePercent] [decimal](8, 4) NULL,
# [MIIndicator] [bit] NULL,
# [MortgageProgram] [varchar](50) NULL,
# [NewConstruction] [bit] NULL,
# [NumberOfMonthsReserve] [int] NULL,
# [NumberOfStories] [tinyint] NULL,
# [OriginationAmount] [money] NULL,
# [OriginatorCompensation] [tinyint] NULL,
# [PerformedDate] [datetime] NULL,
# [Prepay] [bit] NULL,
# [PrepayYears] [tinyint] NULL,
# [ProgramLevel] [varchar](2) NULL,
# [PropertyAppraisedValueAmount] [money] NULL,
# [PropertyCounty] [varchar](100) NULL,
# [PropertyPostalCode] [varchar](20) NULL,
# [PropertyStreetAddress] [varchar](50) NULL,
# [PropertyStreetAddressName] [varchar](50) NULL,
# [PropertyStreetAddressNumber] [varchar](10) NULL,
# [PropertyStreetAddressUnit] [varchar](10) NULL,
# [RateLockType] [varchar](15) NULL,
# [RepresentativeFICOScore] [smallint] NULL,
# [Rural] [bit] NULL,
# [SelfEmployedIndicator] [bit] NULL,
# [SubordinateLienAmount] [money] NULL,
# [SubtractorPercent] [real] NULL,
# [TaxAdvantageMI] [bit] NULL,
# [TimelyPaymentReward] [bit] NULL,
# [UnderwritingMethod] [varchar](50) NULL,
# [UndrawnHelocAmount] [money] NULL,
# [Warrantable] [bit] NULL,
